version: 1.0.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
