version: 1.9.{build}
image: Visual Studio 2017
before_build:
  # Display .NET Core version
- cmd: dotnet --version
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  publish_nuget: false
  include_nuget_references: true
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
